config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get "/", to: redirect("/list")

  get "/:view", to: "events#index", as: :events
  get "/events/:name/:id", to: "events#show", as: :event

  get "/events/count", to: "events#count", as: :event_count
  get "/events/filters", to: "events#filters", as: :event_filters

  resources :wallets, only: [:create]

  namespace :admin do
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["ADMIN_USERNAME"])) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["ADMIN_PASSWORD"]))
    end

    mount Sidekiq::Web, at: '/sidekiq'
  end
end

app/models/event.rb
class Event < ApplicationRecord
  include EventCharacteristics

  enum category: %i(
    meetup
    delegations
    staking_rewards
    pool_rewards
    pool_deposit_refund
    software_releases
    research_papers
    hosksaid
  )

  scope :by_category, ->(category) { where(category: category) }
  scope :between, ->(date_range) { where(start_time: date_range).or(where(end_time: date_range)) }
end

app/models/events/ama.rb
class Events::Ama < ::Event
  # scope :by_presenter, ->(names) { where("extras->'presenter' ?| array[:presenter]", presenter: [names].flatten) }

  filter category: "YouTube", param: "hosksaid", label: "AMA with Charles Hoskinson", default: "on"
  filter category: "Twitter Spaces", param: "hosksaid", label: "AMA with Charles Hoskinson", default: "on"

  def self.count_by_filter(filter, between)
    by_category(filter).between(between).count
  end

  def self.add_summaries_from_hosksaid(ama)
    conn = Faraday.new(url: "https://www.hosksaid.com") { |f| f.response :json }
    response = conn.get("/api/video_summaries/#{ama.extras['external_id']}")
    raise if response.status > 200

    summary = response.body

    description = "<p class='mb-5'>This summary was generated by <a href='https://www.hosksaid.com' target='_blank'>HoskSaid</a> with GPT-4 based on the original transcript.</p>"
    description += summary["sections"].map {|s| "<h5>#{s['topic']}</h5><p>#{s['text']}</p>" }.join
    footer_links = [
      { label: "Summary by hosksaid.com", url: summary["summary_link"] },
      { label: "Watch on YouTube", url: summary["video_url"] }
    ]
    extras = ama.extras
    extras.merge!(
      {
        "footer_links" => footer_links,
        "summarized" => true
      }
    )

    ama.update!(
      description: description,
      extras: extras
    )
  end

  def self.create_from_hosksaid
    conn = Faraday.new(url: "https://www.hosksaid.com") { |f| f.response :json }
    response = conn.get("/api/video_index")

    response.body.each do |video|
      ama = by_category("hosksaid").where("extras->'external_id' ? :id", id: video["id"]).first

      if ama
        # add summary in case it is now available
        if !ama.extras["summarized"] && video["summarized"]
          add_summaries_from_hosksaid(ama)
        else
          next
        end
      end

      # There is no time available.
      # Making it midday UTC to not change the day for all countries behind UTC.
      start_time = Time.parse(video["posted_date"]).utc + 12.hours
      presenter = "Charles Hoskinson"

      ama = new.tap do |event|
        event.category = :hosksaid
        event.name = "#{presenter} - #{video['title']}"
        event.start_time = start_time
        event.end_time = start_time
        event.time_format = "date"
        event.extras = { "presenter" => presenter, "external_id" => video["id"], "summarized" => video["summarized"] }

        event.save!
      end

      add_summaries_from_hosksaid(ama) if video["summarized"]
    end
  end
end

app/models/events/custom.rb
class Events::Custom < OpenStruct
  FILE_PATH = Rails.root.join("config", "events.json").freeze
  ALL = JSON.parse(File.read(FILE_PATH))

  def self.all(between: nil, except: [])
    all = ALL.except(*except)

    if between
      between_dates(all, between)
    else
      all
    end
  end

  def self.categories(except: [])
    @categories ||= all(except: except).keys
  end

  private

    def self.between_dates(data, date_range)
      arr = []

      data.each do |category, events|
        events.map do |event|
          start_time = Time.at(event["start_time"]).in_time_zone
          end_time = Time.at(event["end_time"]).in_time_zone

          if date_range.cover?(start_time..end_time)
            arr << new(
              start_time: start_time,
              end_time: end_time,
              name: event["name"],
              description: event["description"],
              category: category
            )
          end
        end
      end

      arr
    end
end

app/models/events/epoch.rb
class Events::Epoch < OpenStruct
  SHELLY_UNIX = 1596491091
  SHELLY_SLOT = 4924800
  SHELLEY_EPOCH = 209
  SLOTS_PER_EPOCH = 432000

  def self.slot_from_timestamp(timestamp)
    timestamp - SHELLY_UNIX + SHELLY_SLOT
  end

  def self.epoch_from_slot(slot)
    SHELLEY_EPOCH + ((slot - SHELLY_SLOT) / SLOTS_PER_EPOCH)
  end

  def self.epoch_from_timestamp(timestamp)
    epoch_from_slot(
      slot_from_timestamp(timestamp)
    )
  end

  def self.timestamp_from_epoch(epoch)
    seconds = (epoch - SHELLEY_EPOCH) * SLOTS_PER_EPOCH

    Time.at(SHELLY_UNIX + seconds).in_time_zone
  end

  # extend the given time range by the time from the beginning of the range
  # and the start of the first epoch within that range to never cut off any epochs.
  def self.epoch_range_from_time_range(time_range)
    first_epoch = epoch_from_timestamp(time_range.first.to_i)
    last_epoch = epoch_from_timestamp(time_range.last.to_i)

    timestamp_from_epoch(first_epoch)..timestamp_from_epoch(last_epoch + 1)
  end

  def self.all(between: Time.at(SHELLY_UNIX).utc..Time.current.utc, with_events: [])
    Montrose.every(SLOTS_PER_EPOCH.seconds, between: epoch_range_from_time_range(between)).events.map do |date|
      new.tap do |e|
        e.epoch_number = epoch_from_timestamp(date.to_i)
        e.name = "Epoch #{e.epoch_number}"
        e.start_time = timestamp_from_epoch(e.epoch_number)
        e.end_time = e.start_time + SLOTS_PER_EPOCH.seconds
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  helper_method :event_params

  def index
    respond_to do |f|
      f.html do
        @epochs = epochs_with_events(between: helpers.date_range, events_sorted: true)
      end

      f.ics do
        @epochs = epochs_with_events(between: helpers.ics_date_range)

        if request.protocol.start_with?("http")
          send_data ics_calendar.to_ical, type: 'text/calendar', disposition: 'attachment', filename: "cardano-events.ics"
        else
          render plain: ics_calendar.to_ical
        end
      end
    end
  end

  def show
    id = params.fetch(:id)

    if is_active_record_event?(id)
      @event = Event.find(id)
    else
      @event = Events::SimpleEvent.find(id)
    end

    raise ActionController::RoutingError.new('Not Found') unless @event

    respond_to do |f|
      f.turbo_stream
      f.html
    end
  end

  private

  def is_active_record_event?(str)
    !!Integer(str)
  rescue ArgumentError, TypeError
    false
  end

  def epochs_with_events(between:, events_sorted: false)
    events = Events::SimpleEvent.all(except: helpers.filters.off_filters, between: between)
    events += Events::Meetup.where("extras->'group_urlname' ?| array[:names]", names: helpers.filters.on_filters).between(between)

    if helpers.wallet_connected?
      wallet_on_filters = EventFilter.by_class("Events::Wallet").map(&:values).flatten.map(&:keys).flatten - helpers.filters.off_filters
      events += Events::Wallet.by_category(wallet_on_filters).with_stake_address(params[:stake_address]).between(between)
    end

    papers_on_filters = EventFilter.by_class("Events::ResearchPaper").map(&:values).flatten.map(&:keys).flatten - helpers.filters.off_filters
    if papers_on_filters.any?
      papers_on_filters_years = papers_on_filters.map {|f| f.split("-").last }
      events += Events::ResearchPaper.where("extract(year from start_time) IN (#{papers_on_filters_years.join(',')})").between(between)
    end

    events += Events::Software.where("extras->'filter_param' ?| array[:repos]", repos: helpers.filters.on_filters).between(between)

    ama_on_filters = (EventFilter.by_class("Events::Ama").map(&:values).flatten.map(&:keys).flatten - helpers.filters.off_filters).uniq
    events += Events::Ama.by_category(ama_on_filters).between(between) if ama_on_filters.any?

    events = events.sort_by(&:start_time) if events_sorted

    Epoch.all(between: between, with_events: events)
  end

  def ics_calendar
    current_timestamp = Time.current.utc.to_i

    Icalendar::Calendar.new.tap do |cal|
      cal.x_wr_calname = "cardano-calendar.com"
      cal.description = "My Customized Cardano Events"
      cal.refresh_interval = "P4H"

      @epochs.each do |epoch|
        cal.event do |ce|
          ce.summary = epoch.name
          ce.description = "Slots #{epoch.start_slot} – #{epoch.end_slot}"
          ce.categories = "Epoch"
          ce.dtstart = epoch.start_time.utc
          ce.dtend = epoch.end_time.utc
          ce.uid = epoch.id
          ce.sequence = current_timestamp

          epoch.events.each do |event|
            cal.event do |ce|
              ce.summary = event.name
              ce.description = event_url(name: event.urlname, id: event.id)
              ce.dtstart = event.start_time.utc
              ce.categories = event.category
              ce.dtend = event.end_time.utc
              ce.uid = event.id.to_s
              ce.sequence = current_timestamp
            end
          end
        end
      end

      cal.publish
    end
  end

  def event_params
    @event_params ||= params.permit(
      :filter_param, :filter_class,
      :format, :view, :start_date, :tz, :stake_address, filter: {}
    ).to_h.with_indifferent_access.symbolize_keys
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def footer_links(links, button: true)
    links.map do |link|
      label = tag.i(nil, class: "bi bi-box-arrow-up-right ms-2")

      link_css_classes = "btn btn-secondary" if button
      label = link["label"] + label if button

      link_to label.html_safe, link["url"], class: link_css_classes, target: "_blank"
    end
  end

  def render_footer_links(links, button: true)
    footer_links(links).join.html_safe
  end

  def tags(event)
    event.tags.each_with_index.map do |tag_name, idx|
      css_classes = "badge text-bg-info"
      css_classes += " ms-1" if idx > 0

      tag.span tag_name, class: css_classes
    end.join.html_safe
  end

  def epoch_description(epoch, time_range: false, slot: true)
    time = [l(epoch.start_time, format: :short)]
    time << l(epoch.end_time, format: :short) if time_range

    desc = [tag.time(time.join(" – "))]
    desc << tag.p("Slot #{epoch.start_slot}", class: "slot") if slot
    desc << epoch_progress_bar(epoch) unless epoch.future?

    desc.join("")
  end

  def epoch_progress_bar(epoch)
    tag.div(class: "progress mt-3", role: "progressbar", aria: { label: "Epoch Progress", valuemin: "0", valuemax: "100" }) do
      tag.div(class: "progress-bar", style: "width: #{epoch.progress}%") do
        number_to_percentage(epoch.progress, precision: 0)
      end
    end
  end

  def current_epoch_border_gradient(progress)
    colors = [
      "var(--bs-primary) #{progress}%",
      "var(--bs-border-color) #{100-progress}%"
    ].join(',')

    "border-color: unset !important; border-image: linear-gradient(180deg, #{colors}) 1"
  end

  def event_time(event)
    start_time = event.start_time.to_time
    end_time = event.end_time.to_time

    if event.momentary? || event.open_end?
      l(start_time, format: event.time_format&.to_sym || :short)
    elsif event.one_day?
      "#{l(start_time, format: :short)} – #{l(end_time, format: :time)}"
    else
      "#{l(start_time, format: event.time_format&.to_sym || :short)} – #{l(end_time, format: event.time_format&.to_sym || :short)}"
    end
  end

  def event_views
    ["month", "week", "list"]
  end

  def event_view_icon(view)
    view == "list" ? "bi-list-ul" : "bi-calendar-#{view}"
  end

  def render_event_view_switches
    default_classes = "event_view list-group-item list-group-item-action"
    active_classes = "active bg-secondary border-secondary"

    event_views.map do |view|
      classes = current_view == view ? [default_classes, active_classes].join(" ") : default_classes

      link_to events_path(event_params.merge(view: view)), class: classes, data: { action: "click->filters#toggleView", "filters-view-value": view } do
        tag.i(nil, class: "#{event_view_icon(view)} me-1") + view.upcase_first
      end
    end.join.html_safe
  end

  def filter_badge(filter_class, filter_param)
    unless Object.const_defined?(filter_class)
      # todo: implement error tracking
      return nil
    end

    klass = filter_class.constantize

    if klass.respond_to?(:count_by_filter)
      args = [filter_param, date_range]
      args.prepend(current_stake_address) if filter_class == "Events::Wallet"

      count = klass.count_by_filter(*args)

      bg_color = count > 0 ? "bg-success" : "bg-secondary"
      css_classes = "badge position-absolute top-50 end-0 translate-middle rounded-pill #{bg_color}"

      tag.span(count, class: css_classes)
    end
  end

  def render_event_filters
    EventFilterRegistry.registered.sort.to_h.map do |category, filters|
      html_id = category.parameterize

      links = filters.map do |filter_param, filter|
        dataset = {
          "action": "change->filters#toggleFilter",
          "filter-param": filter_param,
          "filter-default": filter[:default]
        }
        checked = event_param_filters.is_on?(filter_param)
        checkbox_name = "filter_#{filter_param}"

        url = event_count_path(
          view: current_view,
          start_date: current_start_date,
          filter_class: filter[:class],
          filter_param: filter_param,
          stake_address: current_stake_address
        )

        frame_id = "#{filter[:class].parameterize}-#{filter_param}"

        badge = turbo_frame_tag(frame_id, class: "turboFrameFilter", loading: "lazy", src: url) do
          tag.div class: "filter_spinner_container position-absolute top-50 end-0 translate-middle" do
            tag.div class: "spinner-border spinner-border-sm", role: "status"
          end
        end

        tag.div class: "event_filter form-switch list-group-item" do
          check_box_tag(checkbox_name, nil, checked, data: dataset, class: "form-check-input me-2 float-none", role: "switch") +
            tag.label(filter[:label], class: "form-check-label small", for: checkbox_name) + badge
        end
      end.join.html_safe

      tag.div class: "accordion-item" do
        filter_accordion_heading(category, html_id) + filter_accordion_body(links, html_id)
      end
    end.join.html_safe
  end

  def filter_list(links)
    tag.ul class: "list-group list-group-flush mb-4" do
      links
    end
  end

  def filter_accordion_heading(title, html_id)
    tag.h2 class: "accordion-header", id: "heading_#{html_id}" do
      tag.button class: "accordion-button collapsed", type: "button", data: { "bs-toggle" => "collapse", "bs-target" => "##{html_id}" }, "aria-expanded" => "false", "aria-controls" => html_id do
        title
      end
    end
  end

  def filter_accordion_body(links, html_id)
    tag.div id: html_id, class: "accordion-collapse collapse", "aria-labelledby" => "heading_#{html_id}", "data-bs-parent" => "#event_filter" do
      tag.div class: "accordion-body p-0" do
        filter_list(links)
      end
    end
  end

  def filters
    @filters ||= EventParamFilters.new(params.fetch(:filter, {}))
  end
  alias_method :event_param_filters, :filters

  def wallet_connected?
    @wallet_connected ||= params[:stake_address] && Wallet.where(stake_address: params[:stake_address]).exists?
  end

  def current_view
    event_params.fetch(:view, "month")
  end

  def current_stake_address
    params.fetch(:stake_address, nil)
  end

  def filter_params
    event_params.fetch(:filter, {}).merge(
      stake_address: event_params[:stake_address])
  end

  def current_start_date
    current_start_time.to_date
  end

  def current_start_time
    event_params.fetch(:start_date, Time.current).to_time
  end

  def date_range
    current_view == "week" ? week_date_range : month_date_range
  end

  def week_date_range
    current_start_time.beginning_of_week..current_start_time.end_of_week
  end

  def month_date_range
    current_start_time.beginning_of_month..current_start_time.end_of_month
  end

  # direction can either be :+ or :- for prev/next
  def start_time(direction=nil)
    return DateTime.current.in_time_zone unless direction

    if current_view == "week"
      date_range.first.public_send(direction, 1.week)
    else
      date_range.first.public_send(direction, 1.month)
    end
  end

  def start_date(direction=nil)
    start_time(direction).to_date
  end

  def url_for_previous_view
    url_for(event_params.merge(
      start_date: start_date(:-).iso8601
    ).merge(view: current_view))
  end

   def url_for_next_view
    url_for(event_params.merge(
      start_date: start_date(:+).iso8601
    ).merge(view: current_view))
  end

  def url_for_today_view
    url_for(
      event_params.merge(
        start_date: start_date.iso8601,
        view: current_view,
        anchor: start_date.iso8601
      )
    )
  end

  def ics_date_range
    Time.at(Epoch::SHELLY_UNIX).utc..(Time.current.utc + 6.months)
  end
end

app/views/events/_list.html.erb
<%= render "navigation", calendar: self %>

<div class="timeline">
  <% @epochs.reverse.each do |epoch| %>
    <div class="row" id="<%= Date.current if epoch.current? %>">
      <% color_class = epoch.future? ? "tertiary" : "primary" %>
      <div class="col-4 col-sm-3 col-md-2 border-<%= color_class %> border-1 border-end pb-5 position-relative text-end" style="<%= current_epoch_border_gradient(epoch.progress) if epoch.current? %>">
        <span class="position-absolute start-100 translate-middle-x p-2 border border-3 border-<%= color_class %> rounded-circle <%= epoch.current? ? 'bg-primary' : 'bg-light' %>"><span class="visually-hidden"></span></span>
        <div class="epoch_time_info d-inline-block pe-3">
          <%= epoch_description(epoch).html_safe %>
        </div>
      </div>

      <div class="col event pb-5 px-4 px-sm-5">
        <h4 class="mb-3 <%= 'text-primary' if epoch.current? %>"><%= epoch.name %></h4>

        <ul class="list-group list-group-flush mt-2">

          <% epoch.events.each do |event| %>
            <li class="list-group-item bg-transparent ps-0 d-relative">
              <time class="text-muted font-monospace me-1"><%= event_time(event) %></time>
              <%= tags(event) %>

              <div class="my-2">
                <%= tag.span event.name %>

                <% if event.description.present? %>
                  <%= link_to event_path(name: event.urlname, id: event.id), class: "ps-1", data: { turbo_stream: true } do %>
                    <i class="bi bi-info-circle"></i>
                  <% end %>
                <% end %>

                <% if event.footer_links.present? %>
                  <%= footer_links(event.footer_links, button: false).first.html_safe %>
                <% elsif event.website.present? %>
                  <%= link_to event.website, target: "_blank", class: "ps-2" do %>
                    <i class="bi bi-box-arrow-up-right"></i>
                  <% end %>
                <% end %>
              </div>
            </li>
          <% end %>

        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_month.html.erb
<%= month_calendar(events: @epochs) do |date, epochs| %>
  <div class="calendar calendar-month card shadow bg-gradient-secondary">
    <div class="card-header position-relative px-2">
      <time datetime="<%= date %>" class="font-monospace"><%= l(date, format: :short) %></time>
      <div class="clipboard" data-controller="clipboard" data-clipboard-success-content-value="Copied!">
        <span class="d-none visually-hidden" data-clipboard-target="source"><%= request.original_url.split("#").first + "##{date}" %></span>
        <a href="#<%= date %>" data-action="clipboard#copy" data-clipboard-target="button">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11.35 3.836c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m8.9-4.414c.376.023.75.05 1.124.08 1.131.094 1.976 1.057 1.976 2.192V16.5A2.25 2.25 0 0118 18.75h-2.25m-7.5-10.5H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V18.75m-7.5-10.5h6.375c.621 0 1.125.504 1.125 1.125v9.375m-8.25-3l1.5 1.5 3-3.75"></path>
          </svg>
        </a>
      </div>
    </div>

    <ul class="list-group list-group-flush">
      <% epochs.each_with_index do |epoch, idx| %>
        <%= tag.li class: "list-group-item position-relative p-2 pb-3", data: { start_time: epoch.start_time.to_i, end_time: epoch.end_time.to_i } do %>
          <% if idx > 0 %>
            <i class="bi bi-chevron-double-down epoch-transition position-absolute start-50 top-0 bg-body translate-middle px-3"></i>
          <% end %>

          <div class="<%= "mt-3" if idx > 0 %>">
            <%= epoch.name %>
            <a href="javascript:void()" class="ms-1" data-controller="popper" data-popper-target="popover" data-bs-title="<%= epoch.name %>" data-bs-content="<%= epoch_description(epoch, time_range: true, slot: false) %>">
              <i class="bi bi-info-circle"></i>
            </a>
          </div>

          <ul class="list-group list-group-flush">
            <% epoch.events.select { |e| (e.start_time.to_date..e.end_time.to_date).include?(date) }.each do |event| %>
              <li class="event list-group-item px-0 py-3">
                <small>
                  <div class="d-flex">
                    <time class="pt-1 me-auto text-muted font-monospace"><%= event_time(event) %></time>
                    <div class="text-end"><%= tags(event) %></div>
                  </div>
                </small>

                <%= tag.div event.name, class: "my-2" %>

                <div class="d-flex">
                  <% if event.description.present? %>
                    <%= link_to event_path(name: event.urlname, id: event.id), class: "me-auto", data: { turbo_stream: true } do %>
                      <i class="bi bi-info-circle"></i>
                    <% end %>
                  <% end %>

                  <% if event.footer_links.present? %>
                    <%= footer_links(event.footer_links, button: false).last.html_safe %>
                  <% elsif event.website.present? %>
                    <%= link_to event.website, target: "_blank" do %>
                      <i class="bi bi-box-arrow-up-right"></i>
                    <% end %>
                  <% end %>
                </div>

              </li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </ul>

  </div>
<% end %>

app/views/events/_offcanvas.html.erb
<div class="offcanvas offcanvas-end" data-controller="filters" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="event_settings" aria-labelledby="event_settings_label" data-turbo-permanent>
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="event_settings_label"></h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>

  <div id="offcanvas-body" class="offcanvas-body" data-filters-target="offcanvasBody" data-preserve-scroll>
    <turbo-frame id="eventFilters" target="_top" loading="lazy" src="<%= event_filters_path({stake_address: current_stake_address}.merge!(filter: event_params.fetch(:filter, {}))) %>">
      <span class="spinner-border position-absolute top-50 start-50"></span>
    </turbo-frame>
  </div>
</div>

app/views/events/_week.html.erb
<%= week_calendar(events: @epochs) do |date, epochs| %>
  <div class="calendar calendar-week card shadow bg-gradient-secondary">
    <div class="card-header position-relative px-2">
      <time datetime="<%= date %>" class="font-monospace"><%= l(date, format: :short) %></time>
    </div>

    <ul class="list-group list-group-flush">
      <% epochs.each_with_index do |epoch, idx| %>
        <%= tag.li class: "list-group-item position-relative p-2 pb-3", data: { start_time: epoch.start_time.to_i, end_time: epoch.end_time.to_i } do %>
          <% if idx > 0 %>
            <i class="bi bi-chevron-double-down epoch-transition position-absolute start-50 top-0 bg-body translate-middle px-3"></i>
          <% end %>

          <div class="mb-2 <%= "mt-2" if idx > 0 %>">
            <%= epoch.name %>
            <a href="javascript:void()" class="ms-1" data-controller="popper" data-popper-target="popover" data-bs-title="<%= epoch.name %>" data-bs-content="<%= epoch_description(epoch, time_range: true, slot: false) %>">
              <i class="bi bi-info-circle"></i>
            </a>
          </div>

          <ul class="list-group list-group-flush">
            <% epoch.events.select { |e| (e.start_time.to_date..e.end_time.to_date).include?(date) }.each do |event| %>
              <li class="event list-group-item px-0 pb-3">
                <small>
                  <div class="d-flex">
                    <time class="pt-1 me-auto text-muted font-monospace"><%= event_time(event) %></time>
                    <div class="text-end"><%= tags(event) %></div>
                  </div>
                </small>

                <%= tag.div event.name, class: "my-2" %>

                <div class="d-flex">
                  <% if event.description.present? %>
                    <%= link_to event_path(name: event.urlname, id: event.id), class: "me-auto", data: { turbo_stream: true } do %>
                      <i class="bi bi-info-circle"></i>
                    <% end %>
                  <% end %>

                  <% if event.footer_links.present? %>
                    <%= footer_links(event.footer_links, button: false).last.html_safe %>
                  <% elsif event.website.present? %>
                    <%= link_to event.website, target: "_blank" do %>
                      <i class="bi bi-box-arrow-up-right"></i>
                    <% end %>
                  <% end %>
                </div>

              </li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </ul>

  </div>
<% end %>

app/views/events/count.html.erb
<% frame_id = "#{event_params[:filter_class].parameterize}-#{event_params[:filter_param]}" %>

<%= turbo_frame_tag frame_id do %>
  <%= filter_badge(event_params[:filter_class], event_params[:filter_param]) %>
<% end %>

app/views/events/filters.html.erb
<%= turbo_frame_tag "eventFilters", target: "_top" do %>
  <div class="container">
    <div class="row align-items-start">

      <div class="col">
        <div class="list-group list-group-horizontal text-center">
          <%= render_event_view_switches %>
        </div>
      </div>

      <div class="col-12 pt-5">
        <div class="accordion accordion-flush">
          <%= render_event_filters %>
        </div>
      </div>
    </div>

    <div class="row pt-5">
      <div class="col">
        <h5>Sync Cardano events directly to your calendar app</h5>

        <p>With our customizable calendar subscription via the iCalendar (<a href="https://en.wikipedia.org/wiki/ICalendar", target="_blank">ICS</a>) format, you can effortlessly integrate and stay up-to-date with Cardano, for free!</p>

        <%= link_to events_url(view: :events, protocol: :webcal, format: :ics), data: { action: "click->filters#updateSubscribeLink" }, class: "d-block btn btn-success", target: "_blank" do %>
          <i class="bi-calendar2-plus me-1"></i> Subscribe
        <% end %>
      </div>
    </div>

  </div>
<% end %>

app/views/events/index.html.erb
<%= render current_view if event_views.include?(current_view) %>
<%= render "offcanvas" %>

<div id="modalContainer"></div>

app/views/events/show.html.erb
<%= render "modal", event: @event, size: "fullscreen" %>